name: All Contributors

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  add-contributor:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'issue_comment' &&
      contains(github.event.comment.body, '@all-contributors')
    steps:
      - name: Add contributor
        uses: all-contributors/all-contributors-action@v1.4.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
